### PR TITLE
add data upgrade

### PR DESCRIPTION
**Pull request by CarlosLH01**
| Hacks | Details            |
| ----- | ------------------ |
| H-1   | Hacks              |
| H-2   | Close Pull Request |
| H-3   | Code Review        |

<br/>

---

### WORKFLOW

```mermaid
sequenceDiagram
    participant feature
    participant develop
    participant main
    feature->>develop: envia feature/foo a la rama develop
    develop->>main: los features en develop a la rama main
```

---

PULL_REQUEST_TEMPLATE

# Tipo de usuario

- [ ] Alfa
- [ ] Bravo
- [ ] Charlie
- [ ] Delta
- [x] Echo

# Tecnología

- [ ] HTML
- [x] Json
- [ ] Archivo plano (.txt)
- [ ] Javascript
- [ ] Markdown / .md

# Seleccione el tipo de actividad

- [ ] Feature
- [x] Changes
- [ ] Hotfix
- [ ] Refactor
- [ ] Performance
- [ ] Testing

### CODE REVIEW

**Comment by Rick6dev** [comment]
No pana no guta

**Comment by CarlosLH01** [comment]
pok´

**Comment by CarlosLH01** [comment]
rechazaaaaaaaaaaaaaa

**Review by Rick6dev — CHANGES_REQUESTED** [review]
eSTA VACIO

**Review by Rick6dev — COMMENTED** [review]
KKK

**Comment by Rick6dev** [comment]
P´P´PI

**Pull request closed without merging**
